Controllers/MemberController.cs
using eCommerce.Data;
using eCommerce.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eCommerce.Controllers;

public class MemberController : Controller
{
    private readonly ProductDbContext _context;
    public MemberController(ProductDbContext context)
    {
        _context = context;
    }
    public IActionResult Register()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Register(RegistrationViewModel reg)
    {
        //map view model to member model tracked by database
        if (ModelState.IsValid) 
        {
            //Check if username or email already exists in database
            bool usernameTaken = await _context.Members.
                                            AnyAsync(m => m.Username == reg.Username);

            if (usernameTaken) 
            {
                ModelState.AddModelError(nameof(Member.Username), "Username already taken");
            }

            bool emailTaken = await _context.Members.
                                        AnyAsync(m => m.Email == reg.Email);

            if (emailTaken)
            {
                ModelState.AddModelError(nameof(Member.Email), "Email already taken");
            }

            if (usernameTaken || emailTaken) 
            { 
                return View(reg);
            }

                Member newMember = new()
            {
                Username = reg.Username,
                Email = reg.Email,
                Password = reg.Password,
                DateOfBirth = reg.DateOfBirth
            };

            _context.Members.Add(newMember);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
        return View(reg);
    }

    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Login(LoginViewModel login) 
    {
        if (ModelState.IsValid) 
        {
            //Check if username or email has match in database
            var loggedInMember = await _context.Members
                                    .Where(m => (m.Username == login.UsernameOrEmail || m.Email == login.UsernameOrEmail)
                                                    && m.Password == login.Password)
                                    .Select(m => new { m.Username, m.MemberId})
                                    .SingleOrDefaultAsync();

            if (loggedInMember == null)
            {
                ModelState.AddModelError(string.Empty, "Your provided credentials do not match any records in our database.");
                return View(login);
            }

            //Log the user in
            HttpContext.Session.SetString("Username", loggedInMember.Username);
            HttpContext.Session.SetInt32("MemberId", loggedInMember.MemberId);

            return RedirectToAction("Index", "Home");
        }
        return View(login);
    }

    public IActionResult Logout() 
    {
        //Clear session
        HttpContext.Session.Clear();
        return RedirectToAction("Index", "Home");
    }
}

Controllers/ProductController.cs
using eCommerce.Data;
using eCommerce.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eCommerce.Controllers;

public class ProductController : Controller
{
    private readonly ProductDbContext _context;
    public ProductController(ProductDbContext context)
    {
        _context = context;
    }
    public async Task<IActionResult> Index(string? searchTerm, decimal? minPrice, decimal? maxPrice, int page = 1)
    {
        const int productsPerPage = 3;

        IQueryable<Product> query = _context.Products;

        //apply filters
        if (!string.IsNullOrWhiteSpace(searchTerm)) 
        { 
            query = query.Where(p => p.Title.ToLower().Contains(searchTerm));
        }
        if (minPrice.HasValue) 
        { 
            query = query.Where(p => p.Price >= minPrice.Value);
        }
        if (maxPrice.HasValue) 
        { 
            query = query.Where(p => p.Price <= maxPrice.Value);
        }

        int totalItems = await _context.Products.CountAsync();
        int totalPagesNeeded = (int)Math.Ceiling((double)totalItems / productsPerPage);

        if (page < 1) 
            page = 1;

        //if user tries to navigate to a page greater than total pages, set to last page
        if (totalPagesNeeded > 0 && page > totalPagesNeeded) page = totalPagesNeeded;

        List<Product> products = await _context.Products
            .OrderBy(p => p.Title)
            .Skip((page - 1) * productsPerPage)
            .Take(productsPerPage)
            .ToListAsync();

        ProductListViewModel productListViewModel = new ProductListViewModel
        {
            Products = products,
            CurrentPage = page,
            TotalPages = totalPagesNeeded,
            PageSize = productsPerPage,
            TotalItems = totalItems,
            SearchTerm = searchTerm,
            MinPrice = minPrice.ToString(),
            MaxPrice = maxPrice.ToString()
        };

        return View(productListViewModel);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Product p)
    {
        if(ModelState.IsValid)
        {
            _context.Products.Add(p);           //Add to database
            await _context.SaveChangesAsync();  //Save changes

            //TempData is used to pass data between actions and will persist over redirect
            TempData["Message"] = $"{p.Title} created successfully!";

            return RedirectToAction("Index");
        }
        return View(p);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        Product? product = await _context.Products.FindAsync(id);

        if (product == null)
        {
            return NotFound();
        }

        return View(product);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Product product)
    {
        if (ModelState.IsValid)
        { 
            _context.Update(product);
            await _context.SaveChangesAsync();

            TempData["Message"] = $"{product.Title} updated successfully!";
            return RedirectToAction(nameof(Index));
        }
        return View(product);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    { 
        Product? product= await _context.Products.FindAsync(id);

        if (product == null)
        {
            return NotFound();
        }

        return View(product);
    }

    [HttpPost]
    [ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        Product? product = _context.Products
            .Where(p => p.ProductId == id)
            .FirstOrDefault();

        if (product == null) 
        { 
            return RedirectToAction(nameof(Index));
        }

        _context.Remove(product);
        await _context.SaveChangesAsync();

        TempData["Message"] = $"{product.Title} deleted successfully!";
        return RedirectToAction(nameof(Index));
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Toast's Tech Trove</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eCommerce.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Toast's Tech Trove</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-link">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="Index">Product Listings</a>
                        </li>

                        @if (Context.Session.GetString("Username") == null)
                        {
                            <li class="nav-link">
                                <a class="nav-link text-dark" asp-controller="Member" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-link">
                                <a class="nav-link text-dark" asp-controller="Member" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-link">
                                <a class="nav-link text-dark" asp-controller="Member" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark"> Hello @Context.Session.GetString("Username")</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.Year - Toast's Tech Trove - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>